### ISSUE TITLE
Obtain extracted features

### ISSUE THREAD

**Issue by Hiii999111** [Pilhyeon/Learning-Action-Completeness-from-Points#1]
Thanks for your job, Is there a link of Baidu cloud ？

**Comment by Pilhyeon** [comment]
Sorry for the late reply.

I asked a friend to upload the feature to the Baidu cloud.

The link and the password are as follows.

link: https://pan.baidu.com/s/16Pgor7DNdwSB8zYleqh2mA
pwd: 1234

Hope this will help.

**Comment by Hiii999111** [comment]
> 
> 
> Sorry for the late reply.
> 
> I asked a friend to upload the feature to the Baidu cloud.
> 
> The link and the password are as follows.
> 
> link: https://pan.baidu.com/s/16Pgor7DNdwSB8zYleqh2mA
> pwd: 1234
> 
> Hope this will help.

Thanks!
